import {StyleSheet} from 'react-native';
export default (styles = StyleSheet.create ({
  OutercontainerHomeContentDropDownSpeechToText: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 12,
    borderRadius: 12,
    paddingVertical: 15,
    zIndex: 1,
  },
  Outercontainer: {
    backgroundColor: '#eaeaea',
    paddingHorizontal: 12,
  },
  OutercontainerHomeContent: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 12,
    marginBottom: 12,
    borderRadius: 12,
    paddingBottom: 25,
  },
  OuterWrapperButtonImageToText: {
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 15,
  },
  OuterWrapperButton: {
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
  },
  spinnerTextStyle: {
    color: '#FFF',
  },
  OutercontainerBoxesTextToTextScreen: {
    borderWidth: 1,
    borderRadius: 12,
    width: 140,
    marginHorizontal: 12,
    marginVertical: 12,
    paddingHorizontal: 8,
    borderColor: '#A8A8A8',
    height: 170,
  },
  OutercontainerHomeContentTextToText: {
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 12,
    marginBottom: 12,
    borderRadius: 12,
  },
  OutercontainerBoxesTextToSpeech: {
    borderWidth: 1,
    borderRadius: 12,
    marginHorizontal: 12,
    marginVertical: 12,
    padding: 12,
    width: 140,
    textAlignVertical: 'center',
    textAlign: 'center',
    borderColor: '#A8A8A8',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  OutercontainerSpeechToText: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginVertical: 12,
  },
  outerWrapperAppOurView: {
    padding: 12,
  },
  OutercontainerBoxes: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 35,
    marginTop: 20,
    width: 140,
    marginHorizontal: 12,
    textAlignVertical: 'center',
    textAlign: 'center',
    borderColor: '#A8A8A8',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF783E',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  OutercontainerDropDown: {
    display: 'flex',
    flexDirection: 'row',
  },
  DropDown: {
    width: 130,
    zIndex: 1,
    elevation: 1,
    position: 'relative',
  },
  AnimatedDropDown: {
    borderWidth: 1,
    display: 'flex',
    borderRadius: 8,
  },
  AnimatedDropDownList: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },

  OuterWrapperAnimatedDropDownList: {
    borderWidth: 1,
    padding: 12,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    position: 'absolute',
    top: 50,
    zIndex: 999,
    backgroundColor: 'white',
    width: '100%',
    elevation: 999,
  },

  DropDownList: {
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'row',
  },
  OutercontainerHomeContentDropDownTextToText: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 12,
    borderRadius: 12,
    paddingVertical: 15,
    zIndex: 1,
  },
  Icon: {
    color: '#F28029',
  },
  Button: {
    width: '100%',
    backgroundColor: '#FF783E',
    color: 'white',
    padding: 12,
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 20,
    borderRadius: 12,
  },
  OutercontainerHeader: {
    display: 'flex',
    flexDirection: 'row',
    padding: 10,
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  HeaderOuterWraperInputinput: {
    width: 250,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 22,
    marginRight: 12,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignItems: 'center',
    fontSize: 40,
    borderWidth: 1,
  },
  TextHomePage: {
    color: 'white',
    fontWeight: '700',
  },
  OutercontainerHomeContentDropDown: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 12,
    borderRadius: 12,
    paddingTop: 15,
    zIndex: 1,
  },
}));
