require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SpeechTranslator' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-voice', :path => '../node_modules/@react-native-voice/voice'

  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-tesseract-ocr', :path => '../node_modules/react-native-tesseract-ocr'

  pod 'RNImageConverter', :path => '../node_modules/react-native-image-converter'

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  pod 'RNVoiceRecorder', :path => '../node_modules/react-native-voice-recorder'

  target 'SpeechTranslatorTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
